spring.application.name=user-service
server.port=${PORT}

#db
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#swagger enabled
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus

eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

eureka.client.healthcheck.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_URL}

logging.level.org.springframework.web=DEBUG
logging.level.org.apache.catalina=DEBUG
eureka.instance.prefer-ip-address=true
eureka.instance.non-secure-port=${PORT}